### ISSUE TITLE
Please help with UnsatisfiedLinkError error

### ISSUE THREAD

**Issue by Chakravarti-Baratam** [ahlashkari/CICFlowMeter#117]
I am faced with linkage error when running `./gradlew exeCMD` and still cannot fix it after spending days. Could you see the root cause?
I am using mac book and intellij editor.

Exception in thread "main" java.lang.UnsatisfiedLinkError: com.slytechs.library.NativeLibrary.dlopen(Ljava/lang/String;)J
        at com.slytechs.library.NativeLibrary.dlopen(Native Method)
        at com.slytechs.library.NativeLibrary.<init>(Unknown Source)
        at com.slytechs.library.JNILibrary.<init>(Unknown Source)
        at com.slytechs.library.JNILibrary.loadLibrary(Unknown Source)
        at com.slytechs.library.JNILibrary.register(Unknown Source)
        at com.slytechs.library.JNILibrary.register(Unknown Source)
        at com.slytechs.library.JNILibrary.register(Unknown Source)
        at org.jnetpcap.Pcap.<clinit>(Unknown Source)
        at cic.cs.unb.ca.jnetpcap.PacketReader.config(PacketReader.java:58)
        at cic.cs.unb.ca.jnetpcap.PacketReader.<init>(PacketReader.java:52)
        at cic.cs.unb.ca.ifm.Cmd.readPcapFile(Cmd.java:130)
        at cic.cs.unb.ca.ifm.Cmd.readPcapDir(Cmd.java:102)
        at cic.cs.unb.ca.ifm.Cmd.main(Cmd.java:75)

**Comment by FabioWasner** [comment]
There seems to be a missing dependency. On my Ubuntu 20 installing libpcap-dev aka

`apt-get install libpcap-dev`

and changing 

`compile group: 'org.jnetpcap', name: 'jnetpcap', version:'1.4.1'`
to 
`compile group: 'jnetpcap', name: 'jnetpcap', version: '1.4.r1425-1g'`

in build.gradle dependencies fixed it.

**Comment by essal0815** [comment]
I'm getting a very similar Issue, so I thought I just write it here.

I can use `./gradlew execCMD`  without any issue, since I found the argument option in build.gradle

But I would like to have rather an executable which I can move around and have close to my data. So I thought ./gradlew distZip would be a great option to get the binary `cfm` but when I run this binary (doesn't matter from where (bin folder or project root) I get also a `UnsatisfiedLinkError`.

Unfortunately I'm not 100% firm into Java and Java library management e.g. with maven and gradle ... 

What am I doing wrong ?

 
` ./build/distributions/CICFlowMeter-4.0/bin/cfm data/in/ data/out`

```
cic.cs.unb.ca.ifm.Cmd You select: data/in/
cic.cs.unb.ca.ifm.Cmd Out folder: data/out
CICFlowMeter found :1 pcap files
==> 1 / 1
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'long com.slytechs.library.NativeLibrary.dlopen(java.lang.String)'
	at com.slytechs.library.NativeLibrary.dlopen(Native Method)
	at com.slytechs.library.NativeLibrary.<init>(Unknown Source)
	at com.slytechs.library.JNILibrary.<init>(Unknown Source)
	at com.slytechs.library.JNILibrary.loadLibrary(Unknown Source)
	at com.slytechs.library.JNILibrary.register(Unknown Source)
	at com.slytechs.library.JNILibrary.register(Unknown Source)
	at com.slytechs.library.JNILibrary.register(Unknown Source)
	at org.jnetpcap.Pcap.<clinit>(Unknown Source)
	at cic.cs.unb.ca.jnetpcap.PacketReader.config(PacketReader.java:58)
	at cic.cs.unb.ca.jnetpcap.PacketReader.<init>(PacketReader.java:52)
	at cic.cs.unb.ca.ifm.Cmd.readPcapFile(Cmd.java:128)
	at cic.cs.unb.ca.ifm.Cmd.readPcapDir(Cmd.java:100)
	at cic.cs.unb.ca.ifm.Cmd.main(Cmd.java:73)
```

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
