### ISSUE TITLE
Question about run cicflowmeter -f hhhh.pcap -c flows.csv 

### ISSUE THREAD

**Issue by GooseSteps** [ahlashkari/CICFlowMeter#118]
![image](https://user-images.githubusercontent.com/61348950/118616324-2d02e600-b7f4-11eb-82df-82009f9a64e9.png)
reading from file hhhh.pcap, link-type EN10MB (Ethernet)
Garbage Collection Began. Flows = 1467
Exception in thread AsyncSniffer:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/scapy/sendrecv.py", line 1210, in _run
    session.on_packet_received(p)
  File "/usr/local/lib/python3.7/site-packages/cicflowmeter/flow_session.py", line 107, in on_packet_received
    self.garbage_collect(packet.time)
  File "/usr/local/lib/python3.7/site-packages/cicflowmeter/flow_session.py", line 125, in garbage_collect
    data = flow.get_data()
  File "/usr/local/lib/python3.7/site-packages/cicflowmeter/flow.py", line 83, in get_data
    flow_iat = get_statistics(self.flow_interarrival_time)
  File "/usr/local/lib/python3.7/site-packages/cicflowmeter/utils.py", line 29, in get_statistics
    iat["mean"] = numpy.mean(alist)
  File "<__array_function__ internals>", line 6, in mean
  File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3420, in mean
    out=out, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/numpy/core/_methods.py", line 190, in _mean
    ret = ret / rcount
  File "/usr/local/lib/python3.7/site-packages/scapy/utils.py", line 130, in __truediv__
    return EDecimal(Decimal.__truediv__(self, Decimal(other)))
TypeError: conversion from numpy.int64 to Decimal is not supported
------------------------------
When I run this command ‘cicflowmeter -f hhhh.pcap -c flows.csv ’, I found the problem mentioned above, how can I solve this problem, thank you

**Comment by mark12138** [comment]
numpy==1.18.0 scipy==1.4.1 scapy==2.4.3 request
i slove it by installing the right versions of those packages

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
