### ISSUE TITLE
Python cicflowmeter don't work

### ISSUE THREAD

**Issue by simosimo88** [ahlashkari/CICFlowMeter#132]
When i run this command "#cicflowmeter -i ens34 -c test.csv" , i get this error, can you help me please.
---------------------------------------------------------------------------------------------------------------------------------
root@SELKS:/home/selks-user# cicflowmeter -i ens34 -c test.csv
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/scapy-2.4.3-py3.7.egg/scapy/sendrecv.py", line 925, in _run
    session.on_packet_received(p)
  File "/usr/local/lib/python3.7/dist-packages/cicflowmeter-0.1.6-py3.7.egg/cicflowmeter/flow_session.py", line 86, in on_packet_received
    flow.add_packet(packet.flags)
TypeError: add_packet() missing 1 required positional argument: 'direction'

**Comment by raikone14** [comment]
hey, any solution for this? I am facing the same issue when I try to convert or try to capture.

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/scapy-2.4.3-py3.8.egg/scapy/sendrecv.py", line 925, in _run
    session.on_packet_received(p)
  File "/usr/local/lib/python3.8/dist-packages/cicflowmeter-0.1.6-py3.8.egg/cicflowmeter/flow_session.py", line 86, in on_packet_received
TypeError: add_packet() missing 1 required positional argument: 'direction

**Comment by souravs17031999** [comment]
@simosimo88 @raikone14 where's this python flowmeter ?

**Comment by mohammadelhaj** [comment]
@raikone14  how did you fix it? I'm having a trouble time capturing network packets with cicflowmeter? can you help if you got it?

**Comment by souravs17031999** [comment]
@mohammadelhaj I wouldn't suggest to use this library anymore since it has already lots of bugs and I had my fair share of months spent trying to run it correctly but wasn't able to do so.
Finally moved on other libraries which are specialized for these purposes (you can search it on github).

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
