### ISSUE TITLE
CFM executable JVM heap shortage

### ISSUE THREAD

**Issue by Str-Gen** [ahlashkari/CICFlowMeter#25]
When using the cfm script to run the software from the command line, the JVM crashes with an out of memory error for the heap. The input file I used is 114MB. The JVM had a max heap size of -XX:MaxHeapSize=4190109696 bytes =~ 4GB. Surely processing a 114MB file shouldn't cause this much memory usage.

The stacktrace
```
Working on... c91e8614-8654-4bac-ac2a-e73a54742e7f.pcap
Exception in thread "DisposableGC" Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.jnetpcap.nio.LinkSequence.iterator(Unknown Source)
	at org.jnetpcap.nio.DisposableGC.sortGenerations(Unknown Source)
	at org.jnetpcap.nio.DisposableGC.drainRefQueueLoop(Unknown Source)
	at org.jnetpcap.nio.DisposableGC$2.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.OutOfMemoryError: Java heap space
	at cic.cs.unb.ca.jnetpcap.FlowGenerator.addPacket(FlowGenerator.java:120)
	at cic.cs.unb.ca.ifm.Cmd.readPcapFile(Cmd.java:144)
	at cic.cs.unb.ca.ifm.Cmd.readPcapDir(Cmd.java:100)
	at cic.cs.unb.ca.ifm.Cmd.main(Cmd.java:73)
```

**Comment by Str-Gen** [comment]
As expected you can work around this limitation by setting the max heap size for the JVM. Edit the cfm script to include a larger than 4G max heap value.
```
# Add default JVM options here. You can also use JAVA_OPTS and CFM_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='-Djava.library.path=../lib/native -Xms2G -Xmx8G'

```

**Comment by ahlashkari** [comment]
Thanks.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
