### ISSUE TITLE
Please help with jnetpcap linkage error

### ISSUE THREAD

**Issue by Jumabek** [ahlashkari/CICFlowMeter#47]
I am faced with linkage error when running `./cfm` and still cannot fix it after spending a day. Could you see the root cause?

Exception in thread "main" java.lang.UnsatisfiedLinkError: com.slytechs.library.NativeLibrary.dlopen(Ljava/lang/String;)J
	at com.slytechs.library.NativeLibrary.dlopen(Native Method)
	at com.slytechs.library.NativeLibrary.<init>(Unknown Source)
	at com.slytechs.library.JNILibrary.<init>(Unknown Source)
	at com.slytechs.library.JNILibrary.loadLibrary(Unknown Source)
	at com.slytechs.library.JNILibrary.register(Unknown Source)
	at com.slytechs.library.JNILibrary.register(Unknown Source)
	at com.slytechs.library.JNILibrary.register(Unknown Source)
	at org.jnetpcap.Pcap.<clinit>(Unknown Source)
	at cic.cs.unb.ca.jnetpcap.PacketReader.config(PacketReader.java:58)
	at cic.cs.unb.ca.jnetpcap.PacketReader.<init>(PacketReader.java:52)
	at cic.cs.unb.ca.ifm.Cmd.readPcapFile(Cmd.java:128)
	at cic.cs.unb.ca.ifm.Cmd.readPcapDir(Cmd.java:100)
	at cic.cs.unb.ca.ifm.Cmd.main(Cmd.java:73)
![Screenshot from 2020-01-15 21-53-17](https://user-images.githubusercontent.com/4343873/72435532-9ed2b600-37e1-11ea-8c3d-86f865e1f749.png)

**Comment by Jumabek** [comment]
Done! The issue turned out to be with `libpcap-dev` prerequisite for linux to use `jnetpcap` which I learned from https://github.com/ahlashkari/CICFlowMeter/issues/9

Made a pull request  https://github.com/ahlashkari/CICFlowMeter/pull/48

**Comment by ahlashkari** [comment]
Thanks @Jumabek

**Comment by wshwhyu** [comment]
@Jumabek could you share your CICFlowMeter tool with me ? my tool   csv generated by the tool  have incorrect calculation of Total Length of Fwd Packets. my email is 349046059@qq.com

**Comment by Jumabek** [comment]
Hi @wshwhyu sorry for late reply. I recommend getting into code and understand how features are computed. Unfortunately i cannot share modified version of CICFLOWMETER for now because it includes my research ideas

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
