### ISSUE TITLE
CLI cfm issue: Crash + CICFlowMeter issue

### ISSUE THREAD

**Issue by Thytu** [ahlashkari/CICFlowMeter#84]
Hello, I am trying to use your project to create an IDS but I encounter two issues.

First one (CLI version (cfm):

When i use cfm (in PATH/CICFlowMeter/build/distributions/CICFlowMeter-4.0/bin/) and doing:
`sudo ./cfm some.pcap`  folder I have a crash:

`cic.cs.unb.ca.ifm.Cmd You select: test_random.pcap
cic.cs.unb.ca.ifm.Cmd Out folder: test
cic.cs.unb.ca.ifm.Cmd CICFlowMeter received 1 pcap file
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.slytechs.library.NativeLibrary.dlopen(Ljava/lang/String;)J
	at com.slytechs.library.NativeLibrary.dlopen(Native Method)
	at com.slytechs.library.NativeLibrary.<init>(Unknown Source)
	at com.slytechs.library.JNILibrary.<init>(Unknown Source)
	at com.slytechs.library.JNILibrary.loadLibrary(Unknown Source)
	at com.slytechs.library.JNILibrary.register(Unknown Source)
	at com.slytechs.library.JNILibrary.register(Unknown Source)
	at com.slytechs.library.JNILibrary.register(Unknown Source)
	at org.jnetpcap.Pcap.<clinit>(Unknown Source)
	at cic.cs.unb.ca.jnetpcap.PacketReader.config(PacketReader.java:58)
	at cic.cs.unb.ca.jnetpcap.PacketReader.<init>(PacketReader.java:52)
	at cic.cs.unb.ca.ifm.Cmd.readPcapFile(Cmd.java:128)
	at cic.cs.unb.ca.ifm.Cmd.main(Cmd.java:80)`

Do you have any ideas ?

My second Issue is with CICFlowMeter in (PATH/CICFlowMeter/build/distributions/CICFlowMeter-4.0/bin/) and doing:
`sudo ./CICFlowMeter`
I do not see any of my network.

Do you have any ideas ?

**Comment by tungnat97** [comment]
Try not running with `sudo`.

**Comment by Thytu** [comment]
> Try not running with `sudo`.

Thank but it do not change any things.
We decided to no longer use CICFlowMeter due to those issues.

**Comment by tungnat97** [comment]
I was using CICFlowMeter also and it was not functioning correctly. What tool are you using?

**Comment by Thytu** [comment]
We are now using Tshark (CLI version of Wireshark).
For more information feel free to check our project: https://github.com/PoCInnovation/SmartShark

**Comment by tungnat97** [comment]
How do you label the dataset used for training? I assume you just label all of the flow extracted from a DDoS pcap file as DDoS.

**Comment by Thytu** [comment]
Yes, we had to do some concessions but the result was pretty efficient

**Comment by sunhanwu** [comment]
Modify the DEFAULT_JVM_OPTS value in the cfm script to your jnetpcap-1.4.r1425, so that no error will be reported
``` bash
DEFAULT_JVM_OPTS='"-Djava.library.path=/home/sunhanwu/tools/CICFlowMeter/jnetpcap/linux/jnetpcap-1.4.r1425/"'
```
